import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Hero from "../components/hero";
import NewsBody from "../components/news_body";
import Contact from "../components/contact";
import Footer from "../components/footer";

export default function News() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sbit-us</title>
        <meta name="description" content="Generated by sbit" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Hero />
        <NewsBody />
        <Contact />
        <Footer />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
